name: Build and Push to ECR

on:
  push:
    branches:
      - dev
    paths:
      - 'client/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      work-dir: ./client
    secrets:
      access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}