name: Client - Build + Push ECR

on:
  push:
    branches: [main, stage]
    paths:
      - 'client/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/ecr-push.yml
    if: github.ref == 'refs/heads/stage'
    with:
      work-dir: client
      aws-region: ${{ vars.STAGE_AWS_REGION }}
      ecr-registry: ${{ vars.STAGE_ECR_REGISTRY }}
      ecr-repository: ${{ vars.STAGE_ECR_REPOSITORY }}
    secrets:
      aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}