name: Client - Build + Push ECR

on:
  push:
    branches:
      - dev
    paths:
      - 'client/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/ecr-push.yml
    with:
      work-dir: client
      environment: Dev
    secrets: inherit