on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string

jobs:
  build-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build + Push
        env:
          ECR_IMAGE: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ inputs.work-dir }}-${{github.sha}}
        run: |
          cd ./${{ inputs.work-dir }} 
          docker build -t $ECR_IMAGE .
          docker push $ECR_IMAGE