on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      ecr-registry:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string

jobs:
  build-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws-region }}
          aws-access-key-id: ${{ secrets.aws-access-key }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build + Push
        env:
          ECR_IMAGE: ${{ inputs.ecr-registry }}/${{ inputs.ecr-repository }}:${{ inputs.work-dir }}-${{github.sha}}
        run: |
          cd ./${{ inputs.work-dir }} 
          docker build -t $ECR_IMAGE .
          docker push $ECR_IMAGE