name: Build and Push to ECR

on:
  push:
    branches:
      - dev
    paths:
      - 'client/**'
      - 'server/**'

jobs:
  BuildAndPushImageToECR:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          ECR_IMAGE: $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
        run: |
          echo $ECR_REGISTRY
          echo $ECR_REPOSITORY
          echo $ECR_IMAGE
          docker build -t $ECR_IMAGE .
          docker push $ECR_IMAGE