on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
    secrets:
      access-key:
        required: true
      secret-key:
        required: true

jobs:
  build-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: $access-key
          aws-secret-access-key: $secret-key

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Build + Push
        env:
          ECR_IMAGE: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:server-${{github.sha}}
        run: |
          cd $work-dir
          docker build -t $ECR_IMAGE .
          docker push $ECR_IMAGE