name: Server - Build + Push ECR

on:
  push:
    branches: [main, stage]
    paths:
      - 'server/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/ecr-push.yml
    with:
      work-dir: server
    secrets: inherit