name: Build and Push to ECR

on:
  push:
    branches:
      - dev
    paths:
      - 'server/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/ecr-push.yml
    with:
      work-dir: server
    secrets: inherit